[package]
name = "rust-uefi-mikan"
version = "0.1.0"
authors = ["Satoshi Kojima <skoji@skoji.jp>"]
edition = "2018"


[dependencies]
uefi = { version = "0.8.0", features = ["exts", "alloc"] }
uefi-services = "0.5.0"

rlibc = "1"