[package]
name = "laranja-kernel"
version = "0.1.0"
authors = ["Satoshi Kojima <skoji@skoji.jp>"]
edition = "2021"

[dependencies]
x86_64 = "0.14.7"
spin = { version = "0.9.2", features = ["lock_api", "mutex"] }

[profile.dev]
panic="abort"



