[package]
name = "laranja-loader"
version = "0.1.0"
authors = ["Satoshi Kojima <skoji@skoji.jp>"]
edition = "2021"


[dependencies]
uefi = { version = "0.10.0", features = ["exts", "alloc", "logger"] }
log = { version = "0.4.11", default-features = false }
elf_rs = "0.1"
